import Groq from 'groq-sdk';

const client = new Groq({ apiKey: process.env.GROQ_API_KEY });

const MODEL = 'llama-3.3-70b-versatile';

const MOBILE_SYSTEM_PROMPT = `
You are MobileForge AI — an expert React Native / Expo developer.
Your job: receive a natural language description of a mobile app and return COMPLETE, WORKING Expo code.

RULES:
1. Always return a single App.tsx file that works standalone in Expo Snack
2. Use only packages available in Expo Snack: react-native, expo-*, @react-navigation/*, react-native-paper, @expo/vector-icons
3. Include beautiful, modern UI — not default RN components
4. If the user writes in Hebrew, the app UI must be in Hebrew with RTL support (I18nManager.forceRTL)
5. Always include: proper navigation structure, loading states, error handling
6. Return ONLY valid JSON — no explanation, no markdown fences, no extra text before or after the JSON

DESIGN PRINCIPLES:
- Use LinearGradient from expo-linear-gradient for headers and backgrounds
- Consistent color palette from the prompt context
- Rounded corners (borderRadius: 12+)
- Proper shadows (elevation on Android, shadowColor/shadowOffset/shadowOpacity/shadowRadius on iOS)
- Use @expo/vector-icons for icons
- Modern card-based layouts with proper spacing

OUTPUT FORMAT — return ONLY this JSON object, nothing else:
{
  "appName": "App name in English",
  "description": "One sentence description",
  "files": {
    "App.tsx": "...full TypeScript/TSX code that works in Expo Snack...",
    "package.json": "{\"dependencies\": {\"expo\": \"~51.0.0\", \"expo-linear-gradient\": \"~13.0.2\", \"@expo/vector-icons\": \"^14.0.2\", \"react-native-paper\": \"5.12.3\"}}"
  },
  "colorScheme": {
    "primary": "#hexcolor",
    "background": "#hexcolor",
    "text": "#hexcolor",
    "accent": "#hexcolor"
  },
  "features": ["feature1", "feature2", "feature3"],
  "hebrewSummary": "תיאור קצר בעברית של מה שנבנה"
}

CRITICAL — JSON ONLY:
- Start your response with { and end with }
- Do NOT wrap in markdown code blocks (no \`\`\` fences)
- Do NOT include any text, explanation, or commentary before or after the JSON
- The entire response must be parseable by JSON.parse()
IMPORTANT: The App.tsx must be complete, self-contained, and immediately runnable in Expo Snack with SDK 51.
`;

export interface ConversationMessage {
  role: 'user' | 'assistant';
  content: string;
}

export interface GeneratedApp {
  appName: string;
  description: string;
  files: Record<string, string>;
  colorScheme: {
    primary: string;
    background: string;
    text: string;
    accent?: string;
  };
  features: string[];
  hebrewSummary: string;
}

function cleanJson(raw: string): string {
  // Strip markdown fences if present
  let cleaned = raw.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/\s*```$/i, '').trim();
  // Find the first { and last } to extract JSON even if there's preamble
  const start = cleaned.indexOf('{');
  const end = cleaned.lastIndexOf('}');
  if (start !== -1 && end !== -1 && end > start) {
    cleaned = cleaned.slice(start, end + 1);
  }
  return cleaned;
}

export async function generateMobileApp(
  userPrompt: string,
  conversationHistory: ConversationMessage[]
): Promise<GeneratedApp> {
  const response = await client.chat.completions.create({
    model: MODEL,
    max_tokens: 8000,
    messages: [
      { role: 'system', content: MOBILE_SYSTEM_PROMPT },
      ...conversationHistory,
      { role: 'user', content: userPrompt },
    ],
  });

  const raw = response.choices[0]?.message?.content || '';

  try {
    return JSON.parse(cleanJson(raw)) as GeneratedApp;
  } catch {
    return {
      appName: 'Generated App',
      description: 'Mobile app generated by MobileForge',
      files: { 'App.tsx': raw },
      colorScheme: { primary: '#6C3AE8', background: '#0A0A0F', text: '#E8E8F0' },
      features: [],
      hebrewSummary: 'האפליקציה נוצרה בהצלחה',
    };
  }
}

// Vision is not supported with Groq/Llama — call sites catch this and return 503
export async function generateFromScreenshot(): Promise<never> {
  throw Object.assign(new Error('Vision not supported'), { code: 'VISION_NOT_SUPPORTED' });
}

export async function* streamGenerateMobileApp(
  userPrompt: string,
  conversationHistory: ConversationMessage[]
): AsyncGenerator<string> {
  const stream = await client.chat.completions.create({
    model: MODEL,
    max_tokens: 8000,
    stream: true,
    messages: [
      { role: 'system', content: MOBILE_SYSTEM_PROMPT },
      ...conversationHistory,
      { role: 'user', content: userPrompt },
    ],
  });

  for await (const chunk of stream) {
    const text = chunk.choices[0]?.delta?.content || '';
    if (text) yield text;
  }
}
