import Anthropic from '@anthropic-ai/sdk';

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY || 'placeholder-for-demo-mode' });

const MOBILE_SYSTEM_PROMPT = `
You are MobileForge AI — an expert React Native / Expo developer.
Your job: receive a natural language description of a mobile app and return COMPLETE, WORKING Expo code.

RULES:
1. Always return a single App.tsx file that works standalone in Expo Snack
2. Use only packages available in Expo Snack: react-native, expo-*, @react-navigation/*, react-native-paper, @expo/vector-icons
3. Include beautiful, modern UI — not default RN components
4. If the user writes in Hebrew, the app UI must be in Hebrew with RTL support (I18nManager.forceRTL)
5. Always include: proper navigation structure, loading states, error handling
6. Return ONLY valid JSON — no explanation, no markdown fences, no extra text before or after the JSON

DESIGN PRINCIPLES:
- Use LinearGradient from expo-linear-gradient for headers and backgrounds
- Consistent color palette from the prompt context
- Rounded corners (borderRadius: 12+)
- Proper shadows (elevation on Android, shadowColor/shadowOffset/shadowOpacity/shadowRadius on iOS)
- Use @expo/vector-icons for icons
- Modern card-based layouts with proper spacing

OUTPUT FORMAT — return ONLY this JSON object, nothing else:
{
  "appName": "App name in English",
  "description": "One sentence description",
  "files": {
    "App.tsx": "...full TypeScript/TSX code that works in Expo Snack...",
    "package.json": "{\"dependencies\": {\"expo\": \"~51.0.0\", \"expo-linear-gradient\": \"~13.0.2\", \"@expo/vector-icons\": \"^14.0.2\", \"react-native-paper\": \"5.12.3\"}}"
  },
  "colorScheme": {
    "primary": "#hexcolor",
    "background": "#hexcolor",
    "text": "#hexcolor",
    "accent": "#hexcolor"
  },
  "features": ["feature1", "feature2", "feature3"],
  "hebrewSummary": "Short description of what was built"
}

IMPORTANT: The App.tsx must be complete, self-contained, and immediately runnable in Expo Snack with SDK 51.
`;

export interface ConversationMessage {
  role: 'user' | 'assistant';
  content: string;
}

export interface GeneratedApp {
  appName: string;
  description: string;
  files: Record<string, string>;
  colorScheme: {
    primary: string;
    background: string;
    text: string;
    accent?: string;
  };
  features: string[];
  hebrewSummary: string;
}

export async function generateMobileApp(
  userPrompt: string,
  conversationHistory: ConversationMessage[]
): Promise<GeneratedApp> {
  const response = await client.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 8000,
    system: MOBILE_SYSTEM_PROMPT,
    messages: [
      ...conversationHistory,
      { role: 'user', content: userPrompt },
    ],
  });

  const raw = response.content[0].type === 'text' ? response.content[0].text : '';

  try {
    // Strip any potential markdown fences if present
    const cleaned = raw.replace(/^```json\s*/i, '').replace(/\s*```$/i, '').trim();
    const parsed = JSON.parse(cleaned);
    return parsed as GeneratedApp;
  } catch {
    // Fallback: wrap the raw output as App.tsx
    return {
      appName: 'Generated App',
      description: 'Mobile app generated by MobileForge',
      files: { 'App.tsx': raw },
      colorScheme: { primary: '#6C3AE8', background: '#0A0A0F', text: '#E8E8F0' },
      features: [],
      hebrewSummary: 'App created successfully',
    };
  }
}

type ImageMimeType = 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp';

function buildImageUserMessage(
  imageBase64: string,
  mimeType: ImageMimeType,
  isSketch: boolean,
  optionalPrompt?: string
): Anthropic.MessageParam {
  const baseInstruction = isSketch
    ? 'This is a hand-drawn wireframe sketch of a mobile app UI. Interpret the layout, components and flow, then build a complete, polished Expo React Native app based on this sketch. Fill in the design details with modern, beautiful styling.'
    : 'This is a screenshot of a mobile app. Clone its UI and functionality as closely as possible: replicate the colors, layout, typography, components and interaction patterns into a complete Expo React Native app.';

  const fullPrompt = optionalPrompt
    ? `${baseInstruction}\n\nAdditional instructions: ${optionalPrompt}`
    : baseInstruction;

  return {
    role: 'user',
    content: [
      {
        type: 'image',
        source: { type: 'base64', media_type: mimeType, data: imageBase64 },
      },
      { type: 'text', text: fullPrompt },
    ],
  };
}

export async function generateFromScreenshot(
  imageBase64: string,
  mimeType: ImageMimeType,
  optionalPrompt?: string,
  isSketch = false
): Promise<GeneratedApp> {
  const response = await client.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 8000,
    system: MOBILE_SYSTEM_PROMPT,
    messages: [buildImageUserMessage(imageBase64, mimeType, isSketch, optionalPrompt)],
  });

  const raw = response.content[0].type === 'text' ? response.content[0].text : '';

  try {
    const cleaned = raw.replace(/^```json\s*/i, '').replace(/\s*```$/i, '').trim();
    return JSON.parse(cleaned) as GeneratedApp;
  } catch {
    return {
      appName: isSketch ? 'Sketched App' : 'Cloned App',
      description: isSketch ? 'App built from sketch' : 'App cloned from screenshot',
      files: { 'App.tsx': raw },
      colorScheme: { primary: '#6C3AE8', background: '#0A0A0F', text: '#E8E8F0' },
      features: [],
      hebrewSummary: isSketch ? 'App created from sketch successfully' : 'App cloned from screenshot successfully',
    };
  }
}

export async function* streamGenerateMobileApp(
  userPrompt: string,
  conversationHistory: ConversationMessage[]
): AsyncGenerator<string> {
  const stream = client.messages.stream({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 8000,
    system: MOBILE_SYSTEM_PROMPT,
    messages: [
      ...conversationHistory,
      { role: 'user', content: userPrompt },
    ],
  });

  for await (const chunk of stream) {
    if (
      chunk.type === 'content_block_delta' &&
      chunk.delta.type === 'text_delta'
    ) {
      yield chunk.delta.text;
    }
  }
}
